## MERGING DATA USING PANDAS

### BASIC MERGING

In [1]:
import pandas as pd

In [4]:
df1=pd.DataFrame({
    "id":[1,2,3],
    "name":["asha","binu","cathy"]
})

df2=pd.DataFrame({
    "id":[1,2,4],
    "marks":[90,80,85]
})

merged_df=pd.merge(df1,df2,on="id")
print(merged_df)

   id  name  marks
0   1  asha     90
1   2  binu     80

## TYPES OF JOINS

### 1.Inner Join(default)
#### Only Common Raws:

In [5]:
pd.merge(df1,df2,on="id",how="inner")

   id  name  marks
0   1  asha     90
1   2  binu     80

### 2.Left Join
#### All Raws From Left DataFrame:

In [6]:
pd.merge(df1,df2,on="id",how="left")

   id   name  marks
0   1   asha   90.0
1   2   binu   80.0
2   3  cathy    NaN

### 3.Right Join
#### All Raws From Right DataFrame:

In [7]:
pd.merge(df1,df2,on="id",how="right")

   id  name  marks
0   1  asha     90
1   2  binu     80
2   4   NaN     85

### 4.Outer Join
#### All Rows From Both:

In [8]:
pd.merge(df1,df2,on="id",how="outer")

   id   name  marks
0   1   asha   90.0
1   2   binu   80.0
2   3  cathy    NaN
3   4    NaN   85.0

## Merge On Different Column Names

In [9]:
df1=pd.DataFrame({
    "id":[1,2,3],
    "name":["asha","binu","cathy"]
})

df2=pd.DataFrame({
    "student_id":[1,2,4],
    "marks":[90,80,85]
})
merged_df=pd.merge(
    df1,
    df2,
    left_on="id",
    right_on="student_id"
)
merged_df

   id  name  student_id  marks
0   1  asha           1     90
1   2  binu           2     80

## CONCATENATION
### Row Wise:

In [10]:
pd.concat([df1,df2],axis=0)

    id   name  student_id  marks
0  1.0   asha         NaN    NaN
1  2.0   binu         NaN    NaN
2  3.0  cathy         NaN    NaN
0  NaN    NaN         1.0   90.0
1  NaN    NaN         2.0   80.0
2  NaN    NaN         4.0   85.0

### Column Wise:

In [11]:
pd.concat([df1,df2],axis=1)

   id   name  student_id  marks
0   1   asha           1     90
1   2   binu           2     80
2   3  cathy           4     85

# APPLY

In [12]:
marks=pd.Series([45,60,75,90])
def grade(x):
    if x>50:
        return"pass"
    else:
        return"fail"
print(marks.apply(grade))

0    fail
1    pass
2    pass
3    pass
dtype: object

#### Apply Using Lambda Function

In [13]:
marks=pd.Series([45,60,75,90])
result=marks.apply(lambda x:x+5)
print(result)

0    50
1    65
2    80
3    95
dtype: int64

### Apply On DataFrame Columns

In [15]:
df=pd.DataFrame({
    "math":[80,90,95],
    "science":[89,98,70]
})
print(df.apply(max))

math       95
science    98
dtype: int64