In [3]:
import pandas as pd

## Basic Merging:

In [11]:
df1=pd.DataFrame({
    "ID":[1,2,3,4,5],
    "Class":[10,9,10,8,9],
    "Name":["fidha","jalva","mufeeda","shibna","yusra"]
})
df2=pd.DataFrame({
    "ID":[1,2,3,6,7],
    "Marks":[90,96,80,78,95],
    "Grade":["A+","A+","A","B","A+"]
})
pd.merge(df1,df2,on="ID")

   ID  Class     Name  Marks Grade
0   1     10    fidha     90    A+
1   2      9    jalva     96    A+
2   3     10  mufeeda     80     A

## Inner Join:

In [8]:
pd.merge(df1,df2,on="ID",how="inner")

   ID  Class     Name  Marks Grade
0   1     10    fidha     90    A+
1   2      9    jalva     96    A+
2   3     10  mufeeda     80     A

## Left Join:

In [12]:
pd.merge(df1,df2,on="ID",how="left")

   ID  Class     Name  Marks Grade
0   1     10    fidha   90.0    A+
1   2      9    jalva   96.0    A+
2   3     10  mufeeda   80.0     A
3   4      8   shibna    NaN   NaN
4   5      9    yusra    NaN   NaN

## Right Join:

In [13]:
pd.merge(df1,df2,on="ID",how="right")

   ID  Class     Name  Marks Grade
0   1   10.0    fidha     90    A+
1   2    9.0    jalva     96    A+
2   3   10.0  mufeeda     80     A
3   6    NaN      NaN     78     B
4   7    NaN      NaN     95    A+

## Outer Join:

In [14]:
pd.merge(df1,df2,on="ID",how="outer")

   ID  Class     Name  Marks Grade
0   1   10.0    fidha   90.0    A+
1   2    9.0    jalva   96.0    A+
2   3   10.0  mufeeda   80.0     A
3   4    8.0   shibna    NaN   NaN
4   5    9.0    yusra    NaN   NaN
5   6    NaN      NaN   78.0     B
6   7    NaN      NaN   95.0    A+

## Merge On Different Column Names

In [17]:
df1=pd.DataFrame({
    "ID":[1,2,3,4,5],
    "Class":[10,9,10,8,9],
    "Name":["fidha","jalva","mufeeda","shibna","yusra"]
})
df2=pd.DataFrame({
    "Student_ID":[1,2,3,6,7],
    "Marks":[90,96,80,78,95],
    "Grade":["A+","A+","A","B","A+"]
})
pd.merge(df1,
         df2,
         left_on="ID",
         right_on="Student_ID"
)

   ID  Class     Name  Student_ID  Marks Grade
0   1     10    fidha           1     90    A+
1   2      9    jalva           2     96    A+
2   3     10  mufeeda           3     80     A

## CONCATENATION

In [19]:
pd.concat([df1,df2],axis=0)

    ID  Class     Name  Student_ID  Marks Grade
0  1.0   10.0    fidha         NaN    NaN   NaN
1  2.0    9.0    jalva         NaN    NaN   NaN
2  3.0   10.0  mufeeda         NaN    NaN   NaN
3  4.0    8.0   shibna         NaN    NaN   NaN
4  5.0    9.0    yusra         NaN    NaN   NaN
0  NaN    NaN      NaN         1.0   90.0    A+
1  NaN    NaN      NaN         2.0   96.0    A+
2  NaN    NaN      NaN         3.0   80.0     A
3  NaN    NaN      NaN         6.0   78.0     B
4  NaN    NaN      NaN         7.0   95.0    A+

In [20]:
pd.concat([df1,df2],axis=1)

   ID  Class     Name  Student_ID  Marks Grade
0   1     10    fidha           1     90    A+
1   2      9    jalva           2     96    A+
2   3     10  mufeeda           3     80     A
3   4      8   shibna           6     78     B
4   5      9    yusra           7     95    A+

## APPLY

In [23]:
mark=pd.Series([80,89,76,82,90])

def grade(x):
    if x>50:
        return"pass"
    else:
        return"fail"
print(mark.apply(grade))

0    pass
1    pass
2    pass
3    pass
4    pass
dtype: object

### Apply Using Lambda Function

In [25]:
mark=pd.Series([80,89,76,82,90])
result=mark.apply(lambda x:x+5)
print(result)

0    85
1    94
2    81
3    87
4    95
dtype: int64

### Apply On DataFrame Columns

In [28]:
df=pd.DataFrame({
    "maths":[60,90,70,69,80],
    "english":[90,80,78,88,95]
})
print(df.apply(max))

maths      90
english    95
dtype: int64