## Titanic Dataset Analysis Using Pandas

In [9]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [10]:
#load titanic dataset from CSV file
df=pd.read_csv("titanic.csv")

In [11]:
#display first 5 row
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
#display last 5 row
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [13]:
#show number of rows and columns
df.shape

(891, 12)

In [14]:
df.size

10692

In [15]:
#display column names
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [16]:
#show datatypes of all columns
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [17]:
#display complete information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [18]:
#statistical summery of numerical columns
df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [19]:
#check missing values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [20]:
#total missing values in dataset
df.isnull().sum().sum()

np.int64(866)

### Drop rows with missing values df.dropna()

In [21]:
#fill missing age with mean age
df["Age"].fillna(df["Age"].mean(),inplace=True)

In [25]:
#fill missing embarked with mode of embarked
df["Embarked"].fillna(df["Embarked"].mode(0), inplace=True)

In [26]:
df["Cabin"].fillna("Unknow",inplace=True)

In [27]:
#recheking if any null values exist
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

In [18]:
#check for count of duplicate values
df.duplicated().sum()

np.int64(0)

In [19]:
#display specific column
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [20]:
#display multiple columns
df[["Name","Age","Sex"]]

                                                  Name   Age     Sex
0                              Braund, Mr. Owen Harris  None    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  None  female
2                               Heikkinen, Miss. Laina  None  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  None  female
4                             Allen, Mr. William Henry  None    male
..                                                 ...   ...     ...
886                              Montvila, Rev. Juozas  None    male
887                       Graham, Miss. Margaret Edith  None  female
888           Johnston, Miss. Catherine Helen "Carrie"  None  female
889                              Behr, Mr. Karl Howell  None    male
890                                Dooley, Mr. Patrick  None    male

[891 rows x 3 columns]

In [21]:
#display first passenger record
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               None
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                             None
Embarked                          None
Name: 0, dtype: object

In [22]:
#display first five row
df.iloc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,None,1,0,A/5 21171,7.2500,None,None
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,None,1,0,PC 17599,71.2833,None,None
2,3,1,3,"Heikkinen, Miss. Laina",female,None,0,0,STON/O2. 3101282,7.9250,None,None
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,None,1,0,113803,53.1000,None,None
4,5,0,3,"Allen, Mr. William Henry",male,None,0,0,373450,8.0500,None,None

In [23]:
#display row 0 and columns 1 to 3
df.iloc[0,1:4]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Name: 0, dtype: object

In [24]:
#display passengers older than 30
df[df["Age"]>30]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [25]:
#display female passengers
df[df["Sex"]=="female"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,None,1,0,PC 17599,71.2833,None,None
2,3,1,3,"Heikkinen, Miss. Laina",female,None,0,0,STON/O2. 3101282,7.9250,None,None
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,None,1,0,113803,53.1000,None,None
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,None,0,2,347742,11.1333,None,None
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,None,1,0,237736,30.0708,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,None,0,1,230433,26.0000,None,None
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,None,0,0,7552,10.5167,None,None
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,None,0,5,382652,29.1250,None,None
887,888,1,1,"Graham, Miss. Margaret Edith",female,None,0,0,112053,30.0000,None,None
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,None,1,2,W./C. 6607,23.4500,None,None

In [26]:
#count female passengers
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [27]:
#count survived and not survived
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [28]:
#calculate average age
df["Age"].mean()

nan

In [29]:
#find maximum age
df["Age"].max()

nan

In [30]:
#finf minimum age
df["Age"].min()

nan

In [31]:
#calculate median age
df["Age"].median()

np.float64(nan)

In [34]:
#calculate sum of fares
df["Fare"].sum()

np.float64(28693.9493)

In [35]:
#calculate average fare
df["Fare"].mean()

np.float64(32.204207968574636)

In [2]:
#find oldest passenger
df[df["Age"]==df["Age"].max()]

NameError: name 'df' is not defined

In [38]:
#find youngest passenger
df[df["Age"]==df["Age"].min()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [39]:
#sort by age ascending
df.sort_values("Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,None,1,0,A/5 21171,7.2500,None,None
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,None,1,0,PC 17599,71.2833,None,None
2,3,1,3,"Heikkinen, Miss. Laina",female,None,0,0,STON/O2. 3101282,7.9250,None,None
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,None,1,0,113803,53.1000,None,None
4,5,0,3,"Allen, Mr. William Henry",male,None,0,0,373450,8.0500,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,None,0,0,211536,13.0000,None,None
887,888,1,1,"Graham, Miss. Margaret Edith",female,None,0,0,112053,30.0000,None,None
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,None,1,2,W./C. 6607,23.4500,None,None
889,890,1,1,"Behr, Mr. Karl Howell",male,None,0,0,111369,30.0000,None,None
890,891,0,3,"Dooley, Mr. Patrick",male,None,0,0,370376,7.7500,None,None

In [44]:
#sort by age descending
df.sort_values("Age",ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,None,1,0,A/5 21171,7.2500,None,None
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,None,1,0,PC 17599,71.2833,None,None
2,3,1,3,"Heikkinen, Miss. Laina",female,None,0,0,STON/O2. 3101282,7.9250,None,None
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,None,1,0,113803,53.1000,None,None
4,5,0,3,"Allen, Mr. William Henry",male,None,0,0,373450,8.0500,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,None,0,0,211536,13.0000,None,None
887,888,1,1,"Graham, Miss. Margaret Edith",female,None,0,0,112053,30.0000,None,None
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,None,1,2,W./C. 6607,23.4500,None,None
889,890,1,1,"Behr, Mr. Karl Howell",male,None,0,0,111369,30.0000,None,None
890,891,0,3,"Dooley, Mr. Patrick",male,None,0,0,370376,7.7500,None,None

In [45]:
#sort by fare descending
df.sort_values("Fare",ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,None,0,0,PC 17755,512.3292,None,None
737,738,1,1,"Lesurer, Mr. Gustave J",male,None,0,0,PC 17755,512.3292,None,None
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,None,0,1,PC 17755,512.3292,None,None
88,89,1,1,"Fortune, Miss. Mabel Helen",female,None,3,2,19950,263.0000,None,None
27,28,0,1,"Fortune, Mr. Charles Alexander",male,None,3,2,19950,263.0000,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
633,634,0,1,"Parr, Mr. William Henry Marsh",male,None,0,0,112052,0.0000,None,None
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,None,0,0,239853,0.0000,None,None
822,823,0,1,"Reuchlin, Jonkheer. John George",male,None,0,0,19972,0.0000,None,None
732,733,0,2,"Knight, Mr. Robert J",male,None,0,0,239855,0.0000,None,None
674,675,0,2,"Watson, Mr. Ennis Hastings",male,None,0,0,239856,0.0000,None,None

In [47]:
#select passengers from class 1
df[df["Pclass"]==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,None,1,0,PC 17599,71.2833,None,None
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,None,1,0,113803,53.1000,None,None
6,7,0,1,"McCarthy, Mr. Timothy J",male,None,0,0,17463,51.8625,None,None
11,12,1,1,"Bonnell, Miss. Elizabeth",female,None,0,0,113783,26.5500,None,None
23,24,1,1,"Sloper, Mr. William Thompson",male,None,0,0,113788,35.5000,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,None,1,1,11751,52.5542,None,None
872,873,0,1,"Carlsson, Mr. Frans Olof",male,None,0,0,695,5.0000,None,None
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,None,0,1,11767,83.1583,None,None
887,888,1,1,"Graham, Miss. Margaret Edith",female,None,0,0,112053,30.0000,None,None
889,890,1,1,"Behr, Mr. Karl Howell",male,None,0,0,111369,30.0000,None,None

In [48]:
#select passengers from class 2
df[df["Pclass"]==2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,None,1,0,237736,30.0708,None,None
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,None,0,0,248706,16.0000,None,None
17,18,1,2,"Williams, Mr. Charles Eugene",male,None,0,0,244373,13.0000,None,None
20,21,0,2,"Fynney, Mr. Joseph J",male,None,0,0,239865,26.0000,None,None
21,22,1,2,"Beesley, Mr. Lawrence",male,None,0,0,248698,13.0000,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"Duran y More, Miss. Asuncion",female,None,1,0,SC/PARIS 2149,13.8583,None,None
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,None,1,0,P/PP 3381,24.0000,None,None
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,None,0,1,230433,26.0000,None,None
883,884,0,2,"Banfield, Mr. Frederick James",male,None,0,0,C.A./SOTON 34068,10.5000,None,None
886,887,0,2,"Montvila, Rev. Juozas",male,None,0,0,211536,13.0000,None,None

In [49]:
#select passengers from class 3
df[df["Pclass"]==3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,None,1,0,A/5 21171,7.2500,None,None
2,3,1,3,"Heikkinen, Miss. Laina",female,None,0,0,STON/O2. 3101282,7.9250,None,None
4,5,0,3,"Allen, Mr. William Henry",male,None,0,0,373450,8.0500,None,None
5,6,0,3,"Moran, Mr. James",male,None,0,0,330877,8.4583,None,None
7,8,0,3,"Palsson, Master. Gosta Leonard",male,None,3,1,349909,21.0750,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,None,0,0,7552,10.5167,None,None
884,885,0,3,"Sutehall, Mr. Henry Jr",male,None,0,0,SOTON/OQ 392076,7.0500,None,None
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,None,0,5,382652,29.1250,None,None
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,None,1,2,W./C. 6607,23.4500,None,None
890,891,0,3,"Dooley, Mr. Patrick",male,None,0,0,370376,7.7500,None,None

In [51]:
#count passengers in each class
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [52]:
#average age by passenger class
df.groupby("Pclass")["Age"].mean()

Pclass
1    NaN
2    NaN
3    NaN
Name: Age, dtype: object

In [54]:
#average fare by passenger class
df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [55]:
#survival count by gender
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [56]:
#average age by gender
df.groupby("Sex")["Age"].mean()

Sex
female    NaN
male      NaN
Name: Age, dtype: object

In [57]:
#rename column
df.rename(columns={"Sex":"Gender"})

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,None,1,0,A/5 21171,7.2500,None,None
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,None,1,0,PC 17599,71.2833,None,None
2,3,1,3,"Heikkinen, Miss. Laina",female,None,0,0,STON/O2. 3101282,7.9250,None,None
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,None,1,0,113803,53.1000,None,None
4,5,0,3,"Allen, Mr. William Henry",male,None,0,0,373450,8.0500,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,None,0,0,211536,13.0000,None,None
887,888,1,1,"Graham, Miss. Margaret Edith",female,None,0,0,112053,30.0000,None,None
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,None,1,2,W./C. 6607,23.4500,None,None
889,890,1,1,"Behr, Mr. Karl Howell",male,None,0,0,111369,30.0000,None,None
890,891,0,3,"Dooley, Mr. Patrick",male,None,0,0,370376,7.7500,None,None

In [59]:
#add new column age+5
df["Age_after_5_years"]=df["Age"]+5

In [60]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_after_5_years
0,1,0,3,"Braund, Mr. Owen Harris",male,None,1,0,A/5 21171,7.2500,None,None,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,None,1,0,PC 17599,71.2833,None,None,NaN
2,3,1,3,"Heikkinen, Miss. Laina",female,None,0,0,STON/O2. 3101282,7.9250,None,None,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,None,1,0,113803,53.1000,None,None,NaN
4,5,0,3,"Allen, Mr. William Henry",male,None,0,0,373450,8.0500,None,None,NaN

In [28]:
#add age category column
df["Age_Group"]=df["Age"].apply(
    lambda x:"Child" if x < 18 else"Adult"
)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknow,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknow,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknow,S,Adult

In [70]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_after_5_years
0,1,0,3,"Braund, Mr. Owen Harris",male,None,1,0,A/5 21171,7.2500,None,None,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,None,1,0,PC 17599,71.2833,None,None,NaN
2,3,1,3,"Heikkinen, Miss. Laina",female,None,0,0,STON/O2. 3101282,7.9250,None,None,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,None,1,0,113803,53.1000,None,None,NaN
4,5,0,3,"Allen, Mr. William Henry",male,None,0,0,373450,8.0500,None,None,NaN

In [71]:
#display unique embarkation values
df["Embarked"].unique

<bound method Series.unique of 0      None
1      None
2      None
3      None
4      None
       ...
886    None
887    None
888    None
889    None
890    None
Name: Embarked, Length: 891, dtype: object>

In [72]:
#count unique embarkation values
df["Embarked"].value_counts()

Series([], Name: count, dtype: int64)

In [73]:
#save modified dataset
df.to_csv("new_titanic.csv",index=False)